management.endpoints.web.exposure.include: health,info,prometheus

kafka.streams.sample-streams:
  input-topic: input
  output-topic: prediction
  properties:
    metrics.recording.level: TRACE
    bootstrap.servers: localhost:29092
    application.id: streams-with-external-call
    max.poll.records: 20
    max.poll.interval.ms: 6000